title: Jarred Sutton's Full Stack Portfolio
description: A website that I built to demonstrate both my frontend web development skills as well as current projects. In addition there are fun facts and easter eggs throughout!
